// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Models;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20241224111014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsAvailable = true,
                            Price = 60000m,
                            ProductName = "iPhone 14"
                        },
                        new
                        {
                            ProductId = 2,
                            IsAvailable = true,
                            Price = 70000m,
                            ProductName = "iPhone 15"
                        },
                        new
                        {
                            ProductId = 3,
                            IsAvailable = true,
                            Price = 80000m,
                            ProductName = "iPhone 16"
                        },
                        new
                        {
                            ProductId = 4,
                            IsAvailable = true,
                            Price = 90000m,
                            ProductName = "iPhone 16 Pro"
                        },
                        new
                        {
                            ProductId = 5,
                            IsAvailable = true,
                            Price = 100000m,
                            ProductName = "iPhone 16 Pro Max"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
